// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqjqmzyrwwgcbnbpvlpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxanFtenlyd3dnY2JuYnB2bHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzIwNjYsImV4cCI6MjA3MTA0ODA2Nn0.O9jtcBcNqORhk9moY1fciC_8WS6rm5bgI8RRZeSUvFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});